# Generated by Django 2.2.2 on 2019-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0002_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=45)),
            ],
        ),
    ]
