# Generated by Django 2.2.2 on 2019-06-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0007_auto_20190624_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
