# Generated by Django 2.2.2 on 2019-06-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0008_auto_20190624_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'verbose_name_plural': 'Capabilities'},
        ),
    ]
