# Generated by Django 2.2.2 on 2019-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0009_auto_20190624_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
    ]
