# Generated by Django 2.2.2 on 2019-06-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0010_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
    ]
