# Generated by Django 2.2.2 on 2019-06-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0014_remove_customer_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Ledger.Sector'),
            preserve_default=False,
        ),
    ]
