# Generated by Django 2.2.2 on 2019-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0016_auto_20190626_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='apr',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='aug',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='dec',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='feb',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='jan',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='jul',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='jun',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='mar',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='may',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='nov',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='oct',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q3',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q4',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='sep',
            field=models.IntegerField(default=None),
        ),
    ]
