# Generated by Django 2.2.2 on 2019-06-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0019_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
