# Generated by Django 2.2.2 on 2019-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0020_budget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
