# Generated by Django 2.2.2 on 2019-06-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0021_auto_20190627_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='q4',
        ),
    ]
