# Generated by Django 2.2.2 on 2019-06-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0022_auto_20190627_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
