# Generated by Django 2.2.2 on 2019-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0024_auto_20190628_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='q1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q3',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='budget',
            name='q4',
            field=models.IntegerField(default=None),
        ),
    ]
