# Generated by Django 2.2.3 on 2019-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesQuery', '0027_auto_20190701_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
