# Generated by Django 2.2.3 on 2019-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0028_auto_20190716_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
