# Generated by Django 2.2.3 on 2019-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0029_auto_20190718_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.AddField(
            model_name='sale',
            name='apr',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='aug',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='dec',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='feb',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='jan',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='jul',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='jun',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='mar',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='may',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='nov',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='oct',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='q1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='q2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='q3',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='q4',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='sep',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
