# Generated by Django 2.2.3 on 2019-07-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0030_auto_20190722_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='capability',
        ),
    ]
