# Generated by Django 2.2.3 on 2019-07-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0031_remove_sale_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Ledger.Sector'),
        ),
    ]
